### ISSUE TITLE
Add "Expected number of players" to multiplayer runs

### ISSUE THREAD

**Issue by Gyoo** [oengusio/oengusio#200] opened 2024-11-11 07:06 UTC
### What is the feature?

A new field in the submission form that allows the creator of a multiplayer run to tell how many runners they should have on their run.

### Describe the feature

Right now, there is no way to tell if a multiplayer run has been joined by all the runners. This feature would help marathon organizers to know if a multiplayer run is complete.

### Additional context

In the submission form, field should be available only if the run is different from Single Run.
In the submissions list, this could be displayed next to the run type in parenthesis. For instance : "(Race, # players)"

**Comment by duncte123** [comment] 2024-11-11 07:17
Duplicate of https://github.com/oengusio/oengusio/issues/175

**Closed by duncte123** 2024-11-11 07:17 UTC
Labels: feature
